Create clients list
SinitsaBogdan/project-integrator-multimedia-solutions pull request #44
Opened 2024-06-07 12:59 UTC by Platon-develop

2024-06-07 13:45 UTC, SinitsaBogdan requested changes
Требуются небольшие правки, а так все отлично!

2024-06-07 13:45 UTC, SinitsaBogdan commented on blocks/client/Client.css
> +	opacity: 30%;
сделай не 30, а 50 - 60
что бы не так сильно затемнялось

2024-06-07 13:45 UTC, SinitsaBogdan commented on data/data-clients.js
> +		logo: '../../assets/svg/sber.svg',
тут лучше добавить новое поле name
что бы в html выводить logo + name

2024-06-07 13:45 UTC, SinitsaBogdan commented on scripts/create-clients-list.js
> +		for (let i = 0; i < 12; i++) {
ограничение тоже лучше оптимизировать

сделать не через for а к примеру через константу с числом
и if в конце

2024-06-07 17:02 UTC, Platon-develop commented on scripts/create-clients-list.js
> +		for (let i = 0; i < 12; i++) {
Тут for только для работоспособности скрипта, его можно убрать, но тогда один элемент только выведется. По сути схема така я как в списке лицензий

2024-06-08 09:07 UTC, SinitsaBogdan requested changes

2024-06-08 09:07 UTC, SinitsaBogdan commented on data/data-clients.js
> +		name: '',
Тут "Сбербанк"
и эту переменную выводить в html через js

2024-06-08 09:09 UTC, Platon-develop commented on data/data-clients.js
> +		name: '',
Так у нас название в логотипе есть. Если не было то было бы название

2024-06-08 09:14 UTC, closed without merging